Add backoff policy
aiven/aiven-kafka-connect-s3 pull request #74
Opened 2021-04-14 14:45 UTC by willyborankin

Added 4 new properties to control back off policies:
 - `kafka.retry.backoff.ms` - Kafka retry backoff in milliseconds
 - `aws.s3.backoff.delay.ms` - S3 default base sleep time for non-throttled exceptions in milliseconds
 - `aws.s3.backoff.max.delay.ms` - S3 maximum back-off time before retrying a request in milliseconds
 - `aws.s3.backoff.max.retries` - Maximum retry limit

2021-04-29 08:26 UTC, willyborankin commented
move them to draft so far. and will re-open it after command new version has been released

2021-05-06 14:27 UTC, AnatolyPopov requested changes
Some comments

2021-05-06 14:28 UTC, willyborankin commented on src/main/java/io/aiven/kafka/connect/s3/S3SinkTask.java
> +    S3SinkTask(final SinkTaskContext context) {
fixed

2021-05-06 14:29 UTC, willyborankin commented on src/main/java/io/aiven/kafka/connect/s3/S3SinkTask.java
> +        this.s3Client = createAmazonS3Client(config);
its old code for me it is ok

2021-05-06 15:15 UTC, AnatolyPopov approved these changes

2021-05-06 15:16 UTC, merged